// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "todolist": Application User Types
//
// Command:
// $ goagen
// --design=todoApp/design
// --out=$(GOPATH)\src\todoApp
// --version=v1.3.1

package client
