consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  GoaExampleTodolist:
    description: A todo of todolist (default view)
    example:
      href: Non voluptas ipsa rerum facilis qui eum.
      id: 5307900238346589931
      name: Tempore possimus omnis sed temporibus sapiente veritatis.
    properties:
      href:
        description: API href for making requests on the todo
        example: Non voluptas ipsa rerum facilis qui eum.
        type: string
      id:
        description: Unique todo ID
        example: 5307900238346589931
        format: int64
        type: integer
      name:
        description: Name of todo
        example: Tempore possimus omnis sed temporibus sapiente veritatis.
        type: string
    required:
    - id
    - href
    - name
    title: 'Mediatype identifier: application/vnd.goa.example.todolist+json; view=default'
    type: object
host: localhost:8080
info:
  description: A simple goa service
  title: The virtual todolist
  version: ""
paths:
  /todolist/{todoID}:
    get:
      description: Get todo by id
      operationId: todolist#show
      parameters:
      - description: Todo ID
        in: path
        name: todoID
        required: true
        type: integer
      produces:
      - application/vnd.goa.example.todolist+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/GoaExampleTodolist'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show todolist
      tags:
      - todolist
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  NotFound:
    description: Not Found
  OK:
    description: OK
    schema:
      $ref: '#/definitions/GoaExampleTodolist'
schemes:
- http
swagger: "2.0"
