// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "todolist": Application Controllers
//
// Command:
// $ goagen
// --design=todoApp/design
// --out=$(GOPATH)\src\todoApp
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// TodolistController is the controller interface for the Todolist actions.
type TodolistController interface {
	goa.Muxer
	Show(*ShowTodolistContext) error
}

// MountTodolistController "mounts" a Todolist resource controller on the given service.
func MountTodolistController(service *goa.Service, ctrl TodolistController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewShowTodolistContext(ctx, req, service)
		if err != nil {
			return err
		}
		return ctrl.Show(rctx)
	}
	service.Mux.Handle("GET", "/todolist/:todoID", ctrl.MuxHandler("show", h, nil))
	service.LogInfo("mount", "ctrl", "Todolist", "action", "Show", "route", "GET /todolist/:todoID")
}
