// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "todolist": Application Media Types
//
// Command:
// $ goagen
// --design=todoApp/design
// --out=$(GOPATH)\src\todoApp
// --version=v1.3.1

package app

import (
	"github.com/goadesign/goa"
)

// A todo of todolist (default view)
//
// Identifier: application/vnd.goa.example.todolist+json; view=default
type GoaExampleTodolist struct {
	// API href for making requests on the todo
	Href string `form:"href" json:"href" yaml:"href" xml:"href"`
	// Unique todo ID
	ID int `form:"id" json:"id" yaml:"id" xml:"id"`
	// Name of todo
	Name string `form:"name" json:"name" yaml:"name" xml:"name"`
}

// Validate validates the GoaExampleTodolist media type instance.
func (mt *GoaExampleTodolist) Validate() (err error) {

	if mt.Href == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "href"))
	}
	if mt.Name == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "name"))
	}
	return
}
